services:
  - type: web
    name: studentunionbot
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: BotToken
        sync: false
    dockerfilePath: ./Dockerfile
    # Persistent Disk для збереження бази даних між деплоями
    disk:
      name: bot-database
      mountPath: /app/Data
      sizeGB: 1
