services:
  # PostgreSQL Database
  - type: pserv
    name: studentunionbot-db
    env: docker
    plan: free
    databases:
      - name: studentunionbot
        user: studentunionbot
    
  # Telegram Bot
  - type: web
    name: studentunionbot
    env: docker
    plan: free
    branch: production  # Деплоїмо тільки з гілки production
    healthCheckPath: /
    envVars:
      - key: BotToken
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: studentunionbot-db
          property: connectionString
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    dockerfilePath: ./Dockerfile
